---
sidebar: sidebar 
permalink: oci/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure 
summary: 新增 Oracle Cloud Infrastructure（OCI）憑證，以便 Workload Factory 擁有在您的 OCI 帳戶中部署和管理雲端資源所需的權限。 
---
= 將 Oracle Cloud Infrastructure 憑證新增至 NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
新增並管理您的雲端供應商憑證，以便 NetApp Workload Factory 擁有部署和管理雲端供應商帳戶中資源所需的權限。

link:permissions-oci.html["OCI NetApp 儲存服務的權限"]

.關於此任務
您可以從「憑證」頁面新增憑證至現有的 Workload Factory 帳戶。這將為 Workload Factory 提供管理雲端環境中的資源和流程所需的權限。

.開始之前
您需要擁有登入 Oracle Cloud Infrastructure 帳戶的憑證。

.步驟
. 登入  https://console.netapp.com/["NetApp Console"^]。
. 從選單中選擇 *工作負載* > *管理* > *憑證*。
. 在「憑證」頁面上，選擇 *新增憑證*。
. 在「新增 Oracle Cloud Infrastructure NetApp 儲存服務憑證」頁面上，執行下列操作：
+
.. 在 _權限組態_ 下，為 Oracle Cloud Infrastructure NetApp Storage Service 憑證選擇適當的權限。*檢視、規劃與分析* 權限為預設。此權限原則可讓您檢視 OCI NSS 儲存資源池、了解系統健全狀況、取得系統的架構完善分析，並探索節省方案。
.. 依照使用 Oracle Cloud Console 所提供的手冊步驟，完成 OCI NSS 憑證的權限組態。
.. 在 _憑證名稱_ 下，輸入您要用於這些憑證的名稱，然後輸入租用戶 OCID。


. 選擇 *Add* 。


.接下來
link:quick-start-oci.html["NetApp Workload Factory 中的 Oracle Cloud Infrastructure NetApp 儲存服務快速入門。"]
