---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: 已知限制是指本產品版本不支援或無法與之正確互通的平台、設備或功能。 
---
= NetApp Workload Factory 中 FSx for ONTAP 工作負載的已知限制
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
已知限制是指本產品版本不支援或無法與之正確互通的平台、設備或功能。以下限制僅適用於 NetApp Workload Factory 中的 Amazon FSx for NetApp ONTAP。請仔細閱讀這些限制。



[[known-limitations-of-fsx-for-ontap-storage-workloads]]
== FSx for ONTAP 儲存設備工作負載的已知限制



[[region-support]]
=== 區域支援

以下AWS區域不受支援：

* 中國地區
* Secret Cloud
* Top Secret Cloud




[[adding-ha-pairs-limitations]]
=== 新增 HA 對限制

* 這項操作大約需要 30 分鐘才能完成。
* 新增 HA 對會限制以下操作：新增更多 HA 對、配置 IOPS、增加 SSD 容量和更新處理量容量。




[[throughput-capacity-region-support]]
=== 處理量容量區域支援



==== 向上擴充部署

所有區域均支援最高 2 GB/s 的縱向擴充組態。以下區域支援最高 4 GB/s 的縱向擴充部署最大處理量：美國東部（俄亥俄州）區域、美國東部（維吉尼亞州北部）區域、美國西部（俄勒岡州）區域和歐洲（愛爾蘭）。



==== 橫向擴展部署

以下地區支援橫向擴充部署最高達 6 GB/s 的最大處理量：美國東部（維吉尼亞州北部和俄亥俄州）、美國西部（加州北部和俄勒岡州）、歐洲（法蘭克福、愛爾蘭和斯德哥爾摩）以及亞太地區（新加坡和雪梨）。



[[capacity-management]]
=== 容量管理

* iSCSI 協定目前不支援 Volume 自動擴充功能。
* 當自動容量管理特色運作時，不允許手冊增加容量。
* 只有擁有啟用自動容量管理特色時所使用的相同權限，才能將其停用。
* 啟用自動容量管理後，需要連結以確保 Volume inode 隨儲存容量的增加而增加。




[[storage-vms]]
=== 儲存 VM

每個 SKU 的儲存設備虛擬機器數量有限制。Workload Factory 不支援建立超出限制的儲存設備虛擬機器。^1^

有關每個檔案系統的最大 SVM 數量，請參閱 AWS 文件中的 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["管理 FSx for ONTAP 儲存設備虛擬機器"^]。



[[iscsi-protocol-support]]
=== iSCSI 傳輸協定支援

* iSCSI 協定僅適用於 FlexVol Volume。^1^
* iSCSI Volume 不支援縮小 Volume 大小。




[[data-protection]]
=== 資料保護

* 快照無法刪除。
* 複寫檔案系統時，檔案系統中的所有 Volume 都使用相同的複寫原則。
* 對於長期保留複寫關係，只有最後一個快照可用於還原。
* 不可變快照不支援以下功能：
+
** 一致性組
** FabricPool
** FlexCache 磁碟區
** SMtape
** SnapMirror 主動同步
** 使用 -schedule 參數的 SnapMirror 原則規則
** SnapMirror 同步
** SVM 資料移動性（用於將 SVM 從來源叢集遷移或重新定位到目的地叢集）






[[storage-savings-calculator]]
=== 儲存節約計算機

儲存節省計算器無法計算下列組態的成本節約效益：

* FSx for Windows File Server：HDD 儲存設備類型
* Elastic Block Store (EBS)：st1、sc1 和標準 Volume 類型
* Elastic File System (EFS)：突發處理量模式




[[aws-secrets-manager-support]]
=== AWS Secrets Manager 支援

使用 Console 代理程式時不支援 AWS Secrets Manager。



[[amazon-s3-access-points-limitation]]
=== Amazon S3 存取點限制

每個儲存設備虛擬機器的 S3 存取點數量上限為 4,000 個。



[[limitations-for-storage-vm-migration-replication]]
=== 儲存 VM 移轉複寫的限制

* Workload Factory 不支援第一代和第二代 FSx for ONTAP 檔案系統之間儲存虛擬機器的遷移複寫。
* 對於在 vserver 上具有 S3 存取點或 ONTAP S3 組態（包括 object-store-server、buckets、users、groups 或 policies）的磁碟區，不支援切換複寫。


附註：

. 適用於 Amazon FSx for NetApp ONTAP




[[known-limitations-of-fsx-for-ontap-database-workloads]]
== FSx for ONTAP 資料庫工作負載的已知限制



[[instance-detection-support]]
=== 執行個體偵測支援

Workload Factory 支援偵測僅在 Amazon Linux 作業系統上執行的 PostgreSQL 執行個體和僅在 Red Hat Enterprise Linux 上執行的 Oracle 執行個體。



[[ami-image-version-support]]
=== AMI 映像版本支援

對於每個 SQL 版本，我們最多只顯示最近四個版本或修訂版的 AMI 映像。我們不允許從早於最新四個版本的 AMI 映像進行安裝。



[[custom-ami]]
=== 自訂 AMI

使用自訂 AMI 進行部署時，假定映像包含安裝媒體。這是 FCI 組態所必需的，原因如下：

* 解除安裝並重新設定以形成 FCI 叢集
* 當選擇與獨立式部署映像中設定的排序規則不同的排序規則時


作為部署的一部分，Workload Factory 不會安裝包含多個 Microsoft SQL Server 執行個體的自訂 AMI。部署過程中只會選擇並設定預設的 Microsoft SQL Server 執行個體。



[[roll-back-and-retry-for-failed-deployments]]
=== 回滾並重試失敗的部署

Workload Factory 不支援針對失敗部署執行回復和重試。您可以從 AWS 的 CloudFormation 主控台回復或重試失敗的堆疊。



[[active-directory-and-dns-resource-rollback]]
=== Active Directory 和 DNS 資源回溯

當您從 AWS 中的 CloudFormation 主控台復原測試或失敗的部署時，下列 DNS 資源不會從 Active Directory 和 DNS 中移除：

* SQL 部署的每個節點至其管理 IP 位址
* 在 FCI 的情況下，將 Windows 叢集名稱指派給 EC2 執行個體的保留輔助 IP 位址
* 將 SQL FCI 名稱指向 FCI 中兩個 EC2 執行個體的兩個保留 IP 位址


您需要手動清理這些內容，或等待網域清除過時的項目。



[[always-on-availability-groups-configuration-support]]
=== Always On 可用度群組組態支援

Workload Factory 不支援管理 Always On 可用度群組組態。



[[custom-encryption-keys]]
=== 自訂加密金鑰

FSx for ONTAP 的自訂加密金鑰不會根據服務適用性列出。您必須選擇適當的金鑰。AWS 代管金鑰會根據服務適用性進行篩選。



[[cloudformation-template]]
=== CloudFormation 範本

下載或複製的 Codebox 產生的 CloudFormation 範本（YAML 檔案）的保留期間有限，只有七天。



[[sandbox-support]]
=== 沙盒支援

從資料庫伺服器最多可建立 90 個沙箱複本。



[[microsoft-sql-server-detection-and-management]]
=== Microsoft SQL Server 偵測與管理

Microsoft SQL Server 偵測結果不會儲存。每次在 Workload Factory 中存取資料庫時，Microsoft SQL Server 偵測都會重新執行，以識別該區域中的 SQL 安裝。



[[explore-savings]]
=== 探索節省成本

在「庫存」標籤中，顯示的每個 Microsoft SQL 執行個體的估計成本是在 FSx for ONTAP 檔案系統層級計算的，而不是針對託管 SQL 執行個體的 Volume。



[[multiple-fsx-for-ontap-file-systems]]
=== 多個 FSx for ONTAP 檔案系統

Workload Factory 不支援為 Microsoft SQL Server 建立或儲存包含多個 FSx for ONTAP 檔案系統的組態。僅支援部署一個 FSx for ONTAP 檔案系統組態。



[[optimization-limitations]]
=== 最佳化限制



==== 運算規模調整最佳化

變更為某些執行個體類型時，網路組態可能會重設，這可能會導致最佳化期間節點連線故障，進而導致作業故障。可能需要手動介入來檢查並更新 DNS 設定與 iSCSI 工作階段。如需有關 EC2 調整大小限制的詳細資訊，請參閱 link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resize-limitations.html["Amazon Elastic Compute Cloud 文件"^]。



==== ONTAP 和作業系統組態最佳化

ONTAP 組態和作業系統組態不支援對多個 SQL Server 執行個體進行批次最佳化。



==== 作業系統修補程式評估以進行最佳化

為最佳化目的而進行的作業系統修補程式評估可能無法在私有網路中運作。該評估依賴 AWS Patch Manager。若要了解如何在私有網路中修補 Windows EC2 執行個體，請參閱 AWS Cloud Operations Blog link:https://aws.amazon.com/blogs/mt/how-to-patch-windows-ec2-instances-in-private-subnets-using-aws-systems-manager/["如何使用 AWS Systems Manager 修補私有子網路中的 Windows EC2 執行個體"^]。



==== 跨區域複寫評估

* 當目標 FSx for ONTAP 檔案系統位於不同的 AWS 帳戶時，最佳化評估無法確定是否使用了跨區域複寫（CRR）。
* Workload Factory 僅評估來源 FSx for ONTAP 檔案系統的 CRR 組態。




[[on-premises-savings-calculation]]
=== 內部部署節省計算

未考慮 Microsoft SQL Server 內部部署儲存設備的 Volume 大小的成本與節省百分比計算。



[[database-host-authentication-when-exploring-savings]]
=== 探索節省效益時的資料庫主機驗證

在某些權限受限的情況下，成功驗證後，探索節省頁面不會載入資料。



[[integration-with-netapp-backup-and-recovery]]
=== 與 NetApp Backup and Recovery 整合

將主機新增至 NetApp Backup and Recovery 以進行保護後，資料庫探索有時會失敗。



[[registering-oracle-on-suse-linux-enterprise-server-12]]
=== 在 SUSE Linux Enterprise Server 12 上註冊 Oracle

在 SUSE Linux Enterprise Server 12 上註冊 Oracle 資料庫時，Workload Factory 不會安裝 Python 相依性。您必須手動設定所需的 Python 版本。Workload Factory 要求最低版本為 3.6；不過，我們建議使用 3.11 版。



[[known-limitations-for-eda-workloads]]
== EDA 工作負載的已知限制



[[operator-permissions-required]]
=== 需要操作員權限

適用於 EDA 的 NetApp Workload Factory 需要操作員權限才能正常運作。
