---
sidebar: sidebar 
permalink: fsx-storage/create-discover-systems.html 
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, availability zones, discover, storage capacity, iops, throughput, security group, security, NetApp Console 
summary: 從 NetApp Console 建立或探索雲端儲存系統，以新增和管理 Volume 及其他資料服務。 
---
= 在 NetApp Console 中建立或探索雲端儲存系統
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
從 NetApp Console 建立或探索雲端儲存系統，以新增和管理 Volume 及其他資料服務。



[[create-a-storage-system]]
== 建立儲存系統

第一步是建立儲存系統。如果您已經在雲端供應商的控制台中建立了儲存系統，則可以<<探索現有的雲端儲存系統,使用 NetApp Console 探索它>>。

.關於此任務
建立檔案系統時會建立儲存設備 VM。

.開始之前
在建立適用於 ONTAP 的 FSx 檔案系統之前，您需要：

* 賦予 Workload Factory 建立 FSx for ONTAP 檔案系統所需權限的 IAM 角色的 ARN。link:permissions-reference-fsx.html["了解如何授予 AWS 帳戶權限"^]。
* 建立 FSx for ONTAP 執行個體的區域和 VPC 資訊。




[[create-an-fsx-for-ontap-file-system]]
== 建立 FSx for ONTAP 檔案系統

您可以使用 _快速建立_ 或 _進階建立_ 來建立 FSx for ONTAP 檔案系統。您也可以使用 Codebox 中提供的下列工具：REST API、CloudFormation 和 Terraform。link:../admin/use-codebox.html#how-to-use-codebox["了解如何使用 Codebox 進行自動化"^]。


NOTE: 從 Codebox 使用 Terraform 時，您複製或下載的程式碼會隱藏 `fsxadmin` 和  `vsadmin` 密碼。執行程式碼時，您需要重新輸入密碼。

[role="tabbed-block"]
====
.快速建立
--
快速建立功能可讓您使用建議的最佳實務組態。建立 FSx for ONTAP 檔案系統後，您可以變更大多數設定。

.步驟
. 從 NetApp Console 選單中，選擇 *儲存設備*，然後選擇 *管理*。
. 從「系統」頁面選取 *新增系統*。
. 選擇 *Amazon Web Services* 作為位置，然後為 Amazon FSx for NetApp ONTAP 選擇 *新增*。
. 在 Create FSx for ONTAP 檔案系統頁面上，選取 *快速建立*。
+
您也可以載入已儲存的組態。

. 在「檔案系統一般組態」下，提供下列資訊：
+
.. *AWS 認證資料*：選擇在 Workload Factory 中新增 AWS 認證資料，或在不使用認證資料的情況下繼續。
.. *檔案系統名稱*：輸入檔案系統的名稱。
.. *區域和 VPC*：選擇檔案系統的區域和 VPC。
.. *部署類型*：選擇部署類型。
+
*** 單一可用區（Single-AZ）部署：透過監控硬體故障並在發生故障時自動取代基礎架構元件來提供可用度。透過在可用區內自動複寫您的資料來保護其免受元件故障影響，進而實現高持久性。
+
對於高效能工作負載，或工作負載從小規模開始逐步橫向擴充到 72 GB/s 處理量和 240 萬 IOPS 的情況，建議採用此組態。

*** 多可用區（Multi-AZ）部署：即使可用區無法使用，也能提供資料的持續可用度。多可用區檔案系統專為業務關鍵型生產工作負載而設計，這些工作負載需要對共享的 ONTAP 檔案資料具備高可用度，並且需要具備跨可用區內建複寫功能的儲存設備。
+
對於需要高達 6 GB/s 處理量或 200,000 IOPS 的工作負載，建議採用這種單一 HA 配對組態。



.. *標籤*：您可以選擇新增最多 50 個標籤。


. 在 *檔案系統詳細資料* 下，提供下列資訊：
+
.. *SSD 儲存容量*：輸入儲存容量並選擇儲存容量單位。
+
*** 對於第一代部署，檔案系統建立後無法減少容量。
*** 對於第二代部署，您可以在檔案系統建立後增加容量。


.. *ONTAP 認證資料*：選用。請輸入您的 ONTAP 使用者名稱和密碼。密碼可以現在或稍後設定。
+
如果您提供的使用者不是 fsxadmin 使用者，且之後您需要重設 fsxadmin 密碼，您可以從 AWS 主控台執行此操作。

.. *SMB/CIFS 設定*：選用。如果您打算使用 SMB/CIFS 協定存取 Volume，則必須在建立檔案系統期間為儲存設備虛擬機器設定 Active Directory。請提供為此檔案系統建立的儲存設備虛擬機器的下列詳細資訊。
+
... *要參加的 Active Directory 網域*：輸入 Active Directory 的完整網域名稱（FQDN）。
... *DNS IP 位址*：輸入最多三個 DNS IP 位址，以逗號分隔。
... *SMB 伺服器 NetBIOS 名稱*：輸入要為儲存設備虛擬機器建立的 Active Directory 電腦物件的 SMB 伺服器 NetBIOS 名稱。這是此儲存設備虛擬機器在 Active Directory 中的名稱。
... *使用者名稱*：輸入您現有 Active Directory 中服務帳戶的使用者名稱。
+
請勿包含網域前綴或後綴。針對 `EXAMPLE\ADMIN`，請使用 `ADMIN`。

... *密碼*：請輸入服務帳戶的密碼。
... *組織單位*：選擇性輸入您打算在其中為 FSx for ONTAP 建立電腦帳戶的組織單位名稱。OU 是您要將檔案系統參加至其中的組織單位辨識路徑名稱。
... *委派管理員群組*：（選用）輸入 Active Directory 中可以管理檔案系統的群組名稱。
+
如果您使用的是 AWS Managed Microsoft AD，則必須指定一個群組，例如 AWS Delegated FSx Administrators、AWS Delegated Administrators，或是對 OU 具有委派權限的自訂群組。

+
如果您要參加自行管理的 AD，請使用 AD 中的群組名稱。預設群組是 `Domain Admins`。





. 開啟 *摘要* 審查您定義的組態。如有需要，您可以在儲存或建立檔案系統之前變更任何設定。
. 儲存或建立檔案系統。


.結果
如果您建立了檔案系統，則新的 FSx for ONTAP 組態將顯示在「系統」頁面上。

您可以透過多種方式管理 FSx for ONTAP 檔案系統，例如從 NetApp Console 中的工作負載、使用 ONTAP System Manager，以及使用 AWS CloudFormation。

--
.進階建立
--
使用進階建立功能，您可以設定所有組態選項，包括可用度、安全性、備份和維護。

.步驟
. 從 NetApp Console 選單中，選擇 *儲存設備*，然後選擇 *管理*。
. 從「系統」頁面選取 *新增系統*。
. 選擇 *Amazon Web Services* 作為位置，然後為 Amazon FSx for NetApp ONTAP 選擇 *新增*。
. 在「建立 FSx for ONTAP 檔案系統」頁面上，選擇 *進階建立*。
+
您也可以載入已儲存的組態。

. 在「檔案系統一般組態」下，提供下列資訊：
+
.. *AWS 認證資料*：選擇在 Workload Factory 中新增 AWS 認證資料，或在不使用認證資料的情況下繼續。
.. *檔案系統名稱*：輸入檔案系統的名稱。
.. *區域和 VPC*：選擇檔案系統的區域和 VPC。
.. *部署類型*：選擇部署類型和檔案系統世代。第二代檔案系統的可用度取決於所選區域。如果所選區域不支援第二代 FSx for ONTAP 檔案系統，則部署類型將切換為第一代。
+
*** 單一可用區（Single-AZ）部署：透過監控硬體故障並在發生故障時自動取代基礎架構元件來提供可用度。透過在可用區內自動複寫您的資料來保護其免受元件故障影響，進而實現高持久性。
+
*檔案系統產生方式*：請選擇下列選項之一：

+
**** *第二代*：建議將此組態用於高效能工作負載，或工作負載從小規模開始，逐步橫向擴充至 72 GB/s 處理量和 240 萬 IOPS 的情況。
**** *第一代*：此組態非常適合需要高達 4 GB/s 或 160,000 IOPS 的工作負載。第一代檔案系統只能增加容量。


*** 多可用區（Multi-AZ）部署：即使可用區無法使用，也能提供資料的持續可用度。多可用區檔案系統專為業務關鍵型生產工作負載而設計，這些工作負載需要對共享的 ONTAP 檔案資料具備高可用度，並且需要具備跨可用區內建複寫功能的儲存設備。
+
*檔案系統產生方式*：請選擇下列選項之一：

+
**** *第二代*：此單一 HA 配對組態建議用於需要高達 6 GB/s 處理量或 200,000 IOPS 的工作負載。在 Multi-AZ 和第二代檔案系統中，容量可依工作負載需求進行增減。
**** *第一代*：此組態非常適合需要高達 4 GB/s 或 160,000 IOPS 的工作負載。第一代檔案系統只能增加容量。




.. *標籤*：您可以選擇新增最多 50 個標籤。


. 在「檔案系統詳細資料」下，提供以下內容：
+
.. *SSD 儲存容量*：輸入儲存容量並選擇儲存容量單位。
+
*** 對於第一代部署，檔案系統建立後無法減少容量。
*** 對於第二代部署，您可以調整容量。


.. *每個 HA 配對的處理量*：選擇每個 HA 配對數量的處理量。第一代檔案系統僅支援一個 HA 配對。
.. *佈建的 IOPS*：請選擇下列選項之一：
+
*** *自動*：對於自動模式，每建立 1 GiB，就會增加 3 個 IOPS。
*** *使用者配置*：對於使用者配置，請輸入 IOPS 值。


.. *ONTAP 認證資料*：選用。請輸入您的 ONTAP 使用者名稱和密碼。密碼可以現在或稍後設定。
+
如果您提供的使用者不是 fsxadmin 使用者，且之後您需要重設 fsxadmin 密碼，您可以從 AWS 主控台執行此操作。

.. *Storage VM 認證資料*：選用。輸入您的使用者名稱。密碼可以專用於此檔案系統，也可以使用與 ONTAP 認證資料相同的密碼。密碼可以現在設定，也可以稍後設定。
.. *SMB/CIFS 設定*：選用。如果您打算使用 SMB/CIFS 協定存取 Volume，則必須在建立檔案系統期間為儲存設備虛擬機器設定 Active Directory。請提供為此檔案系統建立的儲存設備虛擬機器的下列詳細資訊。
+
... *要參加的 Active Directory 網域*：輸入 Active Directory 的完整網域名稱（FQDN）。
... *DNS IP 位址*：輸入最多三個 DNS IP 位址，以逗號分隔。
... *SMB 伺服器 NetBIOS 名稱*：輸入要為儲存設備虛擬機器建立的 Active Directory 電腦物件的 SMB 伺服器 NetBIOS 名稱。這是此儲存設備虛擬機器在 Active Directory 中的名稱。
... *使用者名稱*：輸入您現有 Active Directory 中服務帳戶的使用者名稱。
+
請勿包含網域前綴或後綴。針對 `EXAMPLE\ADMIN`，請使用 `ADMIN`。

... *密碼*：請輸入服務帳戶的密碼。
... *組織單位*：選擇性輸入您打算在其中為 FSx for ONTAP 建立電腦帳戶的組織單位名稱。OU 是您要將檔案系統參加至其中的組織單位辨識路徑名稱。
... *委派管理員群組*：（選用）輸入 Active Directory 中可以管理檔案系統的群組名稱。
+
如果您使用的是 AWS Managed Microsoft AD，則必須指定一個群組，例如 AWS Delegated FSx Administrators、AWS Delegated Administrators，或是對 OU 具有委派權限的自訂群組。

+
如果您要參加自行管理的 AD，請使用 AD 中的群組名稱。預設群組是 `Domain Admins`。





. 在「網路與安全性」部分，提供以下內容：
+
.. *安全性群組*：建立或使用現有的安全性群組。
+
對於新的安全性群組，請參閱 <<Security group details,安全性群組詳細資料>> 以取得安全性群組協定、連接埠和角色的執行摘要。

.. *可用度區*：選擇可用度區和子網路。
+
*** 對於叢集組態節點 1：選擇可用度區和子網路。
*** 對於叢集組態節點 2：選擇可用度區和子網路。


.. *VPC 路由表*：選擇 VPC 路由表以允許用戶端存取 Volume。
.. *端點 IP 位址範圍*：選擇 *VPC 以外的浮動 IP 位址範圍* 或 *輸入 IP 位址範圍* 並輸入 IP 位址範圍。
.. *加密*：從下拉式選單中選擇加密金鑰名稱。


. 在「備份和維護」部分，提供以下內容：
+
.. *Volume backups*：預設啟用每日自動備份。可依需要停用。
+
... *自動備份保留期間*：輸入自動備份的保留天數。
... *每日自動備份所需時間*：選擇*無偏好*（系統會為您選擇每日備份開始時間）或*選擇每日備份開始時間*並指定開始時間。


.. *每週維護所需時間*：選擇*無偏好*（系統將為您選擇每週維護所需時間的開始時間）或*選擇 30 分鐘每週維護所需時間的開始時間*並指定開始時間。


. 儲存或建立檔案系統。


.結果
如果您建立了檔案系統，則新的 FSx for ONTAP 組態將顯示在「系統」頁面上。

您可以透過多種方式管理 FSx for ONTAP 檔案系統，例如從 NetApp Console 中的工作負載、使用 ONTAP System Manager，以及使用 AWS CloudFormation。

--
====


[[discover-an-existing-cloud-storage-system]]
== 探索現有的雲端儲存系統

如果您之前已在 Workload Factory 中提供了雲端儲存供應商的憑證，則可以從「Discoverable systems」頁面自動探索您的儲存系統。您也可以審查可用的資料服務。

.關於此任務
您在一個帳戶內只能探索一次雲端儲存系統，並將其附加至一個工作區。之後可以移除該儲存系統，並將其重新關聯至不同的工作區。

.步驟
. 從 NetApp Console 選單中，選取 *儲存設備*，然後選取 *管理*，接著選取 *Discoverable systems*。
. 顯示已探索的雲端儲存系統數量。選擇 *探索*。
. 選擇一個或多個儲存系統，然後選擇 *探索* 將其新增至「系統」頁面。


[NOTE]
====
* 如果您選擇未命名的儲存系統，系統會提示您輸入系統名稱。
* 如果您選擇的儲存系統沒有從 Console 管理它所需的憑證，系統會提示您選擇具有所需權限的憑證。
* 以下區域不支援探索：中國區域、GovCloud（美國）區域、Secret Cloud 和 Top Secret Cloud。


====
.結果
Console 會在「系統」頁面上顯示您探索到的系統。您可以透過多種方式管理儲存系統，例如從 NetApp Console 中的「工作負載」、使用 ONTAP System Manager，或是使用雲端供應商的儲存管理工具。
