---
sidebar: sidebar 
permalink: gcnv/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials 
summary: 新增 Google Cloud NetApp Volumes 憑證，以便 Workload Factory 擁有部署和管理 Google 帳戶中雲端資源所需的權限。 
---
= 將 Google Cloud NetApp Volumes 憑證新增至 NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
新增並管理您的雲端供應商憑證，以便 NetApp Workload Factory 擁有部署和管理雲端供應商帳戶中資源所需的權限。



[[overview]]
== 概況

您可以從 NetApp Console 的「憑證」頁面新增 Google Cloud NetApp Volumes 憑證。控制台提供引導式設定說明和文件連結，以便您完成所需的 Google Cloud 組態，然後返回完成新增憑證。

使用此工作流程授予 Workload Factory 發現、分析和管理 Google Cloud 環境中的資源所需的權限。

建立憑證分為三個部分：

* 步驟 1：選擇要授予 Workload Factory 的權限層級。
* 步驟 2：建立並驗證 Google Cloud 服務帳戶，然後選擇要管理的 Google Cloud 專案。
* 步驟 3：輸入憑證名稱並新增憑證。


.開始之前
您需要擁有登入 Google Cloud 帳戶的憑證。

.步驟
. 登入  https://console.netapp.com/["NetApp Console"^]。
. 從選單中選擇 *工作負載* > *管理* > *憑證*。
. 在「憑證」頁面上，選擇 *新增憑證*。
. 選擇 *Google Cloud NetApp Volumes* 作為雲端供應商。
. 在新增 Google Cloud NetApp Volumes 憑證頁面上，完成 *權限組態* 下的每個部分。




[[step-1-create-permission-policies]]
=== 步驟 1：建立權限原則

.步驟
. 在 *建立權限原則* 下，*檢視、規劃和分析* 預設為選取狀態。此權限原則可讓您檢視 Google Cloud NetApp Volumes 儲存設備池、了解系統健全狀況、取得系統架構完善的分析報告，並探索節省成本的方法。
. 選用：如果您也希望 Workload Factory 管理 Google Cloud NetApp Volumes 資源並修復組態問題，請選取 *操作和修復*。
. 繼續之前，請先檢閱 link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-set-up-gcnv.html#set-up-a-service-account["設定 Google Cloud NetApp Volumes"^] 的設定說明。




[[step-2-create-the-google-cloud-service-account]]
=== 步驟 2：建立 Google Cloud 服務帳戶

.步驟
. 展開 *設定您的 Google Cloud 環境*。
. 完成顯示的步驟 1-5 以建立 Google Cloud 服務帳戶。
. 複製服務帳戶電子郵件地址。
. 返回 Workload Factory，將電子郵件地址貼上到 *GCP 服務帳戶* 欄位中，然後選擇 *驗證憑證*。
. 驗證完成後，從 *專案* 下拉選單中選擇您希望 Workload Factory 管理的 Google Cloud 專案。注意：在服務帳戶憑證驗證完成之前，專案清單不可用。




[[step-3-enter-the-credentials-name]]
=== 步驟 3：輸入憑證名稱

.步驟
. 展開*憑證名稱*。
. 在 *名稱* 欄位中，請僅使用英數字元輸入憑證名稱。不允許使用特殊字元和空格。
. 選擇 *Add* 。


.結果
Google Cloud NetApp Volumes 憑證已新增至您的帳戶，可用於支援的 Workload Factory 作業。
