---
sidebar: sidebar 
permalink: fsx-eda/requirements.html 
keywords: Builders, FSx, project, projects. eda, electronic design automation, requirements, setup, Workload Factory 
summary: 在開始使用 NetApp Workload Factory 進行 EDA 之前，請確保 NetApp Workload Factory 和 AWS 已正確設定。這包括準備好您的 AWS 登入憑證、已部署的 FSx for ONTAP 檔案系統等等。 
---
= EDA 需求的 Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 NetApp Workload Factory 進行 EDA 之前，請確保 NetApp Workload Factory 和 AWS 已正確設定。這包括準備好您的 AWS 登入憑證、已部署的 FSx for ONTAP 檔案系統等等。

Workload Factory 登入和帳戶:: 您需要link:../setup/sign-up-and-log-in.html["註冊並登入 NetApp Console。"]
AWS 憑證和權限:: 您需要在 Workload Factory 中新增具有讀寫權限的 AWS 憑證，這表示您將以 _讀寫_ 模式使用 Workload Factory 進行 EDA。


目前不支援 _Basic_ 模式和 _Read-only_ 模式權限。


NOTE: 使用延遲監控功能也需要 AWS 憑證，該功能會收集 CloudWatch 計量以進行 Volume 效能分析。若要接收延遲事件通知，請在 Workload Factory 設定中設定通知偏好設定。啟用 NetApp 代管 AI 分析後，即可針對複雜延遲情境使用選用的 AI 分析。link:learn-latency-monitoring.html["了解延遲監控"]。

link:../fsx-storage/add-credentials.html["了解如何在 Workload Factory 中新增 AWS 憑證。"]

FSx for ONTAP 檔案系統:: 您至少需要一個 FSx for ONTAP 檔案系統：
+
--
* EDA 將使用檔案系統來儲存您建立的專案和工作區。
+
此 FSx for ONTAP 檔案系統必須使用 FlexVol Volume。不支援 FlexGroup Volume。

* 您需要知道 AWS FSx for ONTAP 檔案系統所在的 AWS 區域、VPC 和子網路。
* 您至少需要檔案系統中具有下列組態的一個磁碟區：
+
** 該 Volume 必須設定為 NFS 共享。
** 檔案系統必須設定連結。link:../setup/links-overview.html["深入瞭解連結"]。


* 您需要考慮要套用於此部署中的 AWS 資源的標籤鍵/值對（可選）。
+
link:../fsx-storage/create-discover-systems.html["了解如何探索或建立 FSx for ONTAP 檔案系統。"]



--

