---
sidebar: sidebar 
permalink: setup/links-overview.html 
keywords: links, accounts, connectivity, 
summary: Workload Factory 連結可在 Workload Factory 帳戶與一或多個雲端儲存系統之間建立信任關係與連線。 
---
= 了解 NetApp Workload Factory 連結
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory 連結在 Workload Factory 帳戶和一個或多個雲端儲存系統之間建立信任關係和連線。這可讓您直接透過 ONTAP REST API 呼叫，監控及管理某些雲端供應商 API 無法提供的儲存系統功能。

您無需連結即可開始使用 Workload Factory，但在某些情況下，您需要建立一個連結才能解除鎖定 Workload Factory 的所有功能和工作負載能力。



[[why-links-are-beneficial]]
== 連結為何有益

連結之所以有益，是因為它們允許 Workload Factory 執行雲端供應商 API 本身不提供的操作。連結支援高階 ONTAP 功能和自動化，從而增強雲端儲存系統的管理。

以下是使用連結的一些好處：

* 此連結可讓 NetApp Console 將 ONTAP 指令直接傳送至您的雲端儲存系統，帶來超越雲端供應商原生提供的進階 ONTAP 功能。
* 連結運用遠端無伺服器函數來執行程式碼以回應事件。這種無伺服器方法消除了對在 VPC 中執行之執行個體的依賴。




[[how-links-work]]
== 連結的工作原理

連結運用遠端無伺服器運算服務，例如 AWS Lambda 和 Oracle Cloud Infrastructure Functions。這些服務會回應事件執行程式碼，並自動管理該程式碼所需的運算資源。您建立的連結是您的 NetApp 帳戶的一部分，並與對應的雲端供應商帳戶關聯。

建立連結後，您可以將其關聯至一個或多個雲端儲存系統。每個雲端儲存系統在同一個 NetApp 帳戶中只能關聯至一個連結。如果您有多個 NetApp 帳戶，則單一雲端儲存系統可以關聯至不同 NetApp 帳戶下的其他連結。

您可以在 NetApp Console 的「連結」頁面中，為您的雲端儲存系統建立並關聯連結。

您可以使用儲存在 Workload Factory 認證資料服務中的認證資料，或使用雲端供應商的認證資料服務來驗證連結。Workload Factory 不支援變更驗證模式。



[[costs]]
== 成本

您的雲端供應商的無伺服器運算服務所執行的每筆交易都會產生費用。由於它充當兩個系統之間的 Proxy，因此當該服務向檔案系統上的 ONTAP REST API 傳送請求，以及將回應傳送回 Workload Factory 時，都會產生費用。

* link:https://aws.amazon.com/lambda/pricing/["了解更多關於使用 AWS Lambda 的相關成本"^]
* link:https://www.oracle.com/cloud/cloud-native/functions/["深入瞭解與使用 Oracle Cloud Infrastructure Functions 相關的成本"^]




[[when-a-link-is-required]]
== 需要連結時

Workload Factory 需要連結才能顯示某些資訊並執行某些任務。如果您嘗試執行需要連結的操作，但尚未將連結與雲端儲存系統關聯，Workload Factory 會通知您該操作需要連結。

需要連結的功能包括：

* 精心設計的雲端儲存系統組態狀態，可實現主動式維護、可靠性並優化成本效益
* ONTAP EMS 事件監控與警報
* NetApp 自主勒索軟體防護（ARP/AI）
* 增強跨雲端儲存系統的整體容量可觀測性
* 磁碟區和儲存設備虛擬機器資料複寫、管理和監控
* SMB/CIFS 共用與 NFS 匯出原則資源配置與管理
* 雲端儲存系統上的 iSCSI Volume 管理
* 建立和管理自訂保護 SLA 的快照原則
* 用於自動容量管理的 inode 管理增強功能
* 彈性擴充的磁碟區自動成長
* 複製建立與管理，用於即時、就地的資料複製
* 直接從雲端儲存系統顯示其他計量，例如系統版本
* 顯示儲存 VM 和叢集 LIF 詳細資訊，包括角色、端點、節點、IP 位址和狀態




[[related-information]]
== 相關資訊

了解如何建立和關聯以下連結：

* link:../fsx-storage/create-link.html["Amazon FSx for NetApp ONTAP"]
* link:../oci/create-link.html["OCI NetApp 儲存服務"]

